In [92]:
import numpy as np

A = np.random.randn(9, 6)
U, S, V = np.linalg.svd(A, full_matrices=True)

m = A.shape[0]
n = A.shape[1]

Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:n, :n] = np.diag(S)
S = Sigma

assert np.allclose(A, U@(S@V))
assert U.shape == (m, m)
assert V.shape == (n, n)
assert S.shape == (m, n)

np.set_printoptions(precision=2, suppress=True)

print('rank(A) = {}'.format(np.linalg.matrix_rank(A)))
print('2-norm(A) = {}'.format(np.linalg.norm(A,2)))
print('Frobenius-norm(A) = {}'.format(np.linalg.norm(A,'fro')))
print('k_2(A) = {}'.format(np.linalg.cond(A, 2)))
print('A+ =',*np.linalg.pinv(A),sep='\n')
print('A =',*A,sep='\n')

rank(A) = 6
2-norm(A) = 4.913305495189618
Frobenius-norm(A) = 7.896655989020257
k_2(A) = 12.638791029354575
A+ =
[ 0.13  0.03 -0.14 -0.14 -0.07  0.06  0.09  0.07  0.11]
[ 0.13  0.31 -0.56 -0.32  1.92 -0.14 -0.   -0.31  0.69]
[-0.05 -0.11 -0.22  0.37  0.51  0.3  -0.07  0.07  0.12]
[ 0.13 -0.03  0.07 -0.15 -0.08 -0.23  0.02 -0.16  0.23]
[-0.05  0.04  0.24 -0.24 -0.03 -0.03  0.17  0.03  0.2 ]
[ 0.14  0.26 -0.42  0.02  1.08  0.06  0.09 -0.3   0.34]
A =
[ 1.36 -0.31  0.05  1.14 -0.84  0.52]
[-0.12 -0.64 -1.49 -1.39  0.45  1.81]
[-2.14 -0.27  0.24  0.13  1.93  0.22]
[-1.2  -1.01  1.09  1.06 -0.14  1.27]
[-0.88  0.56  0.08 -0.64  0.25 -0.28]
[ 1.01 -0.68  0.68 -1.08  1.18  0.92]
[ 0.53 -1.11 -0.23 -0.53  1.75  2.03]
[ 1.6   1.1   0.6  -1.24  0.09 -2.26]
[ 0.87 -0.1   1.56  2.01  1.06 -0.21]
